CREATE TABLE `or_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sn` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '订单编号',
  `customer_id` bigint(20) DEFAULT NULL COMMENT '客户id',
  `merchant_id` bigint(20) DEFAULT NULL COMMENT '商户id',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态',
  `receiver_name` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '收货人名称',
  `receiver_mobile` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '收货人电话',
  `receiver_address` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '收货人地址',
  `buyer_remark` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '买家备注',
  `goods_tail_amount` decimal(15,2) DEFAULT '0.00' COMMENT '商品总金额',
  `freight_fee` decimal(15,2) DEFAULT '0.00' COMMENT '邮费',
  `discount_amount` decimal(15,2) DEFAULT '0.00' COMMENT '优惠金额',
  `pay_amount` decimal(15,2) DEFAULT '0.00' COMMENT '支付金额',
  `currency_code` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'CNY' COMMENT '货币类型',
  `fetch_start_date` timestamp NULL DEFAULT NULL COMMENT '取衣开始时间',
  `fetch_end_date` timestamp NULL DEFAULT NULL COMMENT '取衣结束时间',
  `deliver_start_date` timestamp NULL DEFAULT NULL COMMENT '送衣开始时间',
  `deliver_end_date` timestamp NULL DEFAULT NULL COMMENT '送衣结束时间',
  `pay_type` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '支付类型',
  `create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sn` (`sn`) USING BTREE,
  KEY `idx_customer_id` (`customer_id`) USING BTREE,
  KEY `idx_merchant_id` (`merchant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;